### ISSUE TITLE
Not Able to add scanned Emulated games

### ISSUE THREAD

**Issue by Uplinkpro** [gittromney/Playnite-NowPlaying#12]
Did an emulated scan with Ryujinx on a folder with single roms all show up in Playnite however when I go to the NowPlaying tab i have it setup with a pretty large cache the games are not showing up as able to be cached. I used the default settings for Ryujinx. (Tried yuzu aswell) Checked all the requirements listed and all the structure meets the requirements. Any idea what could be wrong??

**Comment by gittromney** [comment]
Hi, sorry for the delay.  If you are still having a problem, can you reply with a screenshot of your NowPlaying view panel.  
It should show the NowPlaying Cache Roots section and the NowPlaying Game Caches entries - I just want to see at least the first game in the list, for now.  Something like this:

![Screenshot 2024-01-13 131137](https://github.com/gittromney/Playnite-NowPlaying/assets/126992708/a3cb4fd0-9f5b-4efc-adc8-7328a3fcbc59)

**Comment by gittromney** [comment]
Rereading your post, I want to make sure I understand have far you were able to get with the setup.  It sounds like you were able to specify at least one cache root directory/disk (correct?).  Assuming that's true, it's then not clear to me whether the problem is: 
1) you are able to enable caching for your switch games but not able to INSTALL any caches, or 
2) you cannot enable any of your games for caching
In my post above, I assumed case 1.  But if it's 2,... sorry, this may come across as a 'did you try rebooting windows' response, but did you try to enabling caching using the '+' button under the NowPlaying Game Caches section of the NP tab --OR-- from via the right mouse from the Library tab?
 
<img width="851" alt="image" src="https://github.com/gittromney/Playnite-NowPlaying/assets/126992708/b236c4ac-e85a-440c-a4eb-eb546950e774">

or

<img width="313" alt="image" src="https://github.com/gittromney/Playnite-NowPlaying/assets/126992708/32aa7088-ad9e-4c80-8fd3-ec3f7f525388">

And if so, did you get a popup window like this?

<img width="918" alt="image" src="https://github.com/gittromney/Playnite-NowPlaying/assets/126992708/523feb2a-97e5-4924-8cf4-2c565fb71d81">

**Comment by Uplinkpro** [comment]
> Rereading your post, I want to make sure I understand have far you were able to get with the setup. It sounds like you were able to specify at least one cache root directory/disk (correct?). Assuming that's true, it's then not clear to me whether the problem is:
> 
> 1. you are able to enable caching for your switch games but not able to INSTALL any caches, or
> 2. you cannot enable any of your games for caching
>    In my post above, I assumed case 1.  But if it's 2,... sorry, this may come across as a 'did you try rebooting windows' response, but did you try to enabling caching using the '+' button under the NowPlaying Game Caches section of the NP tab --OR-- from via the right mouse from the Library tab?
> 
> <img alt="image" width="851" src="https://private-user-images.githubusercontent.com/126992708/297187496-b236c4ac-e85a-440c-a4eb-eb546950e774.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzgyNzQsIm5iZiI6MTcwNTY3Nzk3NCwicGF0aCI6Ii8xMjY5OTI3MDgvMjk3MTg3NDk2LWIyMzZjNGFjLWU4NWEtNDQwYy1hNGViLWViNTQ2OTUwZTc3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNTI2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjA5N2I3ZjJiYjM0Mjc5YzU3NDgwYjhjMDZkNTI5MjRkMTdkOTA1MjEyNTdmN2ZkNjA1M2ZlZDNmNGVjNjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IcCaVkv2RXJHqQaZvpBTP-a26MjRJ9a54mNZsnZAjPU">
> or
> 
> <img alt="image" width="313" src="https://private-user-images.githubusercontent.com/126992708/297187826-32aa7088-ad9e-4c80-8fd3-ec3f7f525388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzgyNzQsIm5iZiI6MTcwNTY3Nzk3NCwicGF0aCI6Ii8xMjY5OTI3MDgvMjk3MTg3ODI2LTMyYWE3MDg4LWFkOWUtNGM4MC04ZmQzLWVjM2Y3ZjUyNTM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNTI2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWQzMmE4YWZhNDc3ODE2NzAyYjFkZTA1MjAxMTdmYTg3ZTAxNDUyNTgxYzc4ZTE3ZTI0ZjYwNjgyNTZlMTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b8pRH7tutwLXBQ4AmJzUReGU21Q5_T__XQYQBYK5SZ8">
> And if so, did you get a popup window like this?
> 
> <img alt="image" width="918" src="https://private-user-images.githubusercontent.com/126992708/297201799-523feb2a-97e5-4924-8cf4-2c565fb71d81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzgyNzQsIm5iZiI6MTcwNTY3Nzk3NCwicGF0aCI6Ii8xMjY5OTI3MDgvMjk3MjAxNzk5LTUyM2ZlYjJhLTk3ZTUtNDkyNC04Y2Y0LTJjNTY1ZmI3MWQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNTI2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmRlNjEyZWNjNDYzZDhkNGMyYWMzN2UzYmU5MGIxMjc3ZWI1NjNkMTY3ZjY3YzgxMzk0YTg3ZDA0MmFmY2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m93hwXCbIoibV8aVqugQQkvJmQ7DUfv4L2QeqUzePY8">

Yup that's exactly what happens. Eventually I got it working after a fresh install however. It must have been just a weird bug however now all my library's are doubling when a rescan happens showing both an uninstalled version and an installed version.

**Comment by gittromney** [comment]
Good to hear that caching is now working for you.  

As for the double entries, there isn't a perfect solution for this other than having Playnite be aware of the NowPlaying library.  In the meantime, as a workaround, it's probably best to disable automatic library rescans once you have enabled game caching.  At that point, as your library grows, you can add games individually, OR, if you have a bunch of new games to add, you could temporarily disable caching for games associated with a particular emulator/scanner, do an auto scan to update/grow your Playnite library, and then reenable game caching for those games. 

I've added this info to the recommended emulator setup section.  Hope this helps.

Regards
