### ISSUE TITLE
[BUG] Does not work on games that have more platforms in addition to PC (Windows)

### ISSUE THREAD

**Issue by Rings4** [gittromney/Playnite-NowPlaying#14]
![image](https://github.com/user-attachments/assets/7ef1f97a-9682-4804-9a0d-49ab54611459)
This works

![image](https://github.com/user-attachments/assets/a08e138b-a489-4614-ba7c-6dcbdb168780)
This does not

Why would one work while the other doesn't? They're both under the PC (Windows) platform. The readme states "Are on 'PC (Windows)' with no ROMs or a supported emulated platform with 1 ROM."

If a supported platform is included among the game's platforms, this plugin should work. Could this please be fixed?

**Comment by gittromney** [comment]
Hi, 
I can implement a fix to support that case, assuming it meets all the other criteria like having only 1 play action, etc.. I'm curious as to why you might want to designate a PC(Windows) game as being multiplatform, though (e.g. "PC, PC (Windows)").

BTW, I don't see the the plain "PC" in the default platforms list.  Is that one you defined?  I see PC(Dos), PC(Linux), and PC(Windows).

![Screenshot 2024-08-10 202241](https://github.com/user-attachments/assets/611089e8-3113-4076-b504-7e07c295d78c)

**Comment by Rings4** [comment]
> Hi, I can implement a fix to support that case, assuming it meets all the other criteria like having only 1 play action, etc.. I'm curious as to why you might want to designate a PC(Windows) game as being multiplatform, though (e.g. "PC, PC (Windows)").
> 
> BTW, I don't see the the plain "PC" in the default platforms list. Is that one you defined? I see PC(Dos), PC(Linux), and PC(Windows).
> 
> ![Screenshot 2024-08-10 202241](https://private-user-images.githubusercontent.com/126992708/356848323-611089e8-3113-4076-b504-7e07c295d78c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNDgyMzUsIm5iZiI6MTcyMzM0NzkzNSwicGF0aCI6Ii8xMjY5OTI3MDgvMzU2ODQ4MzIzLTYxMTA4OWU4LTMxMTMtNDA3Ni1iNTA0LTdlMDdjMjk1ZDc4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQwMzQ1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTA3MGYxNjljMDkyMTUyYmM5YzE0ZmIxNjRmYzA3NDY5OTg3Mjc5Nzk4YTZiOTE1N2M1MDU5MGQ4MGM2MGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YZwTb_L1LNp10W4KMqs6qOJnOLa5RBy60T290u9HJlY)

That sounds good, thank you!

I made the PC platform for further filtering my PC games.

**Comment by gittromney** [comment]
Just released a fix for this (v1.3.4).  Lmk if it works out for you.  Thanks.

**Comment by Rings4** [comment]
Thank you, it seems to be working perfectly! I appreciate this very much.
