### ISSUE TITLE
Side bar icon changes to custom text colour after you click on plugin and back off

### ISSUE THREAD

**Issue by Rings4** [gittromney/Playnite-NowPlaying#16]
This is how the plugin looks normally
![image](https://github.com/user-attachments/assets/e80400ea-0958-494a-b249-ebe6afb711cc)

When you click on it, it changes to blue, which is normal behaviour
![image](https://github.com/user-attachments/assets/87e36b49-11d6-43e5-919c-ed945ec5fd61)

However, when you click off of it, it changes to whatever you set your playnite's text colour to be, which doesn't happen with any other plugin
![image](https://github.com/user-attachments/assets/12490b75-fbf7-4100-94a0-e5702647ac89)

**Comment by gittromney** [comment]
Please try out v1.3.6 and let me know if this addresses the issue for you.

The icon color when unselected/inactive, which is incorrect in your 3rd image above, is now taken from the current Theme's SidebarItem Style's Foreground color.   As a result, the Settings option for choosing a Lighter/Darker sidebar icon color was removed.

Note, I tested this solution with a handful of Themes, but it may still have some issues with specific Themes.
--g

**Comment by gittromney** [comment]
v1.4 released today, which implements a more theme-compliant sidebar icon (hopefully). Closing this issue for now
